server:
  port: 9800
  servlet:
    context-path: /api/admin
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://180.201.163.246:43306/ms_admin_dev?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 151425
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: 180.201.163.246
    port: 46379
    password:
    jedis:
      pool:
        max-active: 20
        max-idle: 5
