server:
  port: 9800
  servlet:
    context-path: /api/admin
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meta_sphere_dev?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 151425
  daq-db-datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ms_daq_db_dev?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 151425
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: 127.0.0.1
    port: 6379
    password: 151425
    jedis:
      pool:
        max-active: 20
        max-idle: 5
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: ms-daq-engine
      username: wyx151425
      password: '151425'
      authentication-database: ms-daq-engine
