server:
  port: 9800
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meta_sphere_dev?characterEncoding=utf-8&useSSL=false
    username: root
    password: 151425
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: 192.168.2.202
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
        max-idle: 5
