server:
  port: 9100
  servlet:
    context-path: /api/portal
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://180.201.163.246:41001/meta_sphere_dev?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: wyx151425
    password: MsMysql001@dmin
  #  daq-db-datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://180.201.163.246:41002/ms_daq_engine_dev?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
  #    username: wyx151425
  #    password: MsMysql002@dmin
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#  redis:
#    host: 180.201.163.246
#    port: 42001
#    password: 151425
#    lettuce:
#      pool:
#        min-idle: 2
#        max-idle: 20
#        max-active: 20
#  data:
#    mongodb:
#      host: 180.201.163.246
#      port: 43001
#      database: ms_daq_engine
#      username: wyx151425
#      password: 'MsMongo001@dmin'
#      authentication-database: ms_daq_engine
#      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
